# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-10 21:39
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170210_2215'),
    ]

    operations = [
        
    ]
