# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-10 21:39
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170210_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key',
            field=models.CharField(default=accounts.models.get_activation_key, max_length=40, verbose_name='Kod aktywacyjny (SHA1)'),
        ),
    ]
