# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-12 21:05
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20170211_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[0-9-+ ]{9,20}$', 'Podaj poprawny numer telefonu')], verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='user',
            name='postcode',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{2}\\-?\\d{3}$', 'Podaj poprawny kod pocztowy')], verbose_name='Kod pocztowy'),
        ),
    ]
