# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-12 21:19
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20170212_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, validators=[accounts.models.phone_validator], verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='user',
            name='postcode',
            field=models.CharField(max_length=6, validators=[accounts.models.postcode_validator], verbose_name='Kod pocztowy'),
        ),
    ]
