# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-13 02:55
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20170212_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key',
            field=models.UUIDField(default=uuid.uuid1, verbose_name='Kod aktywacyjny'),
        ),
    ]
