# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-13 03:18
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20170213_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key',
            field=models.CharField(default=uuid.uuid1, max_length=100, unique=True, verbose_name='Kod aktywacyjny'),
        ),
    ]
