# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-13 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, verbose_name='Nazwa')),
                ('description', models.TextField(blank=True, max_length=4000, verbose_name='Opis')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Cena')),
                ('image', models.FileField(default='no_photo.png', upload_to='', verbose_name='Zdjęcie')),
                ('quantity', models.IntegerField(default=0, verbose_name='Ilość')),
            ],
        ),
    ]
