# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-13 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_auto_20170213_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nazwa'),
        ),
    ]
