# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-20 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0004_auto_20170216_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='shop_app.Category', verbose_name='Kategoria'),
        ),
    ]
