# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-26 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0005_auto_20170220_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nazwa kategorii'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='shop_app.Category', verbose_name='Kategorie'),
        ),
    ]
