# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-02 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0008_auto_20170302_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Ilość'),
        ),
    ]
