# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-26 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nazwa')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Cena')),
                ('days', models.IntegerField(max_length=30, verbose_name='Przewidywany czas dostawy (dni)')),
            ],
            options={
                'verbose_name': 'Sposób wysyłki',
                'verbose_name_plural': 'Sposoby wysyłki',
            },
        ),
    ]
