# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-02 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_order_orderproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderproduct',
            options={},
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(1, 'Oczekiwanie na realizację'), (2, 'W trakcie realizacji'), (3, 'Gotowe do wysyłki'), (4, 'Wysłano')], default=1, max_length=1),
        ),
    ]
