# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-19 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_auto_20170319_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Oczekiwanie na realizację'), (2, 'W trakcie realizacji'), (3, 'Gotowe do wysyłki'), (4, 'Wysłano')], default=1, verbose_name='Status'),
        ),
    ]
